name: Setup pixi env
description: Setup pixi environment for Python
inputs:
  cache-number:
    description: 'Cache number to reset cache if pixi.lock has not changed'
    required: true
    type: number
  JFROG_ARTIFACTORY_TOKEN:
    description: 'JFrog Artifactory Token'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: prefix-dev/setup-pixi@v0.9.0
      with:
        pixi-version: v0.54.1
        cache-key: pixi-env${{ inputs.cache-number }}
        cache: true
        locked: true
      env:
        GIT_LFS_SKIP_SMUDGE: 1
