name: Publish to Artifactory
description: Publish package to JFrog Artifactory
inputs:
  build-dir-path:
    description: 'Path to the build directory'
    required: true
    type: string
  artifactory-dir-path:
    description: 'Path for the package in Artifactory containing the repository name'
    required: true
    type: string
  JFROG_ARTIFACTORY_URL:
    description: 'JFrog Artifactory URL'
    required: true
    type: string
  JFROG_ARTIFACTORY_TOKEN:
    description: 'JFrog Artifactory Token'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4.4.1
      env:
        JF_URL: https://${{ inputs.JFROG_ARTIFACTORY_URL }}
        JF_ACCESS_TOKEN: ${{ inputs.JFROG_ARTIFACTORY_TOKEN }}
    - name: Publish package to Artifactory
      shell: bash
      env:
        INPUTS_BUILD_DIR_PATH: ${{ inputs.build-dir-path }}
        INPUTS_ARTIFACTORY_DIR_PATH: ${{ inputs.artifactory-dir-path}}
      run: |
        for file in ${INPUTS_BUILD_DIR_PATH}/*; do
          filename=$(basename "${file}")
          echo "Uploading in: ${INPUTS_ARTIFACTORY_DIR_PATH}: $filename"
          jf rt u ${file} ${INPUTS_ARTIFACTORY_DIR_PATH}/$filename
        done
