default_language_version:
    python: python3
default_stages: [pre-commit,pre-push]
fail_fast: false

ci:
    autoupdate_branch: develop
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
-   repo: https://github.com/MiraGeoscience/pre-commit-hooks
    rev: v1.0.1
    hooks:
    -   id: prepare-commit-msg
    -   id: check-commit-msg
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: \.mdj$
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude: (^\.idea/.*\.xml|\.mdj)$
    -   id: mixed-line-ending
        exclude: ^\.idea/.*\.xml$
