name: Setup conda env
description: Setup conda environment for Python
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Setup conda env
      uses: mamba-org/setup-micromamba@v1
      env:
        PYTHONUTF8: 1
        CONDA_CHANNEL_PRIORITY: strict
        PIP_NO_DEPS: 1 # all dependencies are installed from conda
        FILE_OS_ID: ${{ runner.os == 'Windows' && 'win' || 'linux' }}
      with:
        micromamba-version: 1.5.8-0
        environment-file: 'environments/py-${{ inputs.python-version }}-${{ env.FILE_OS_ID }}-64-dev.conda.lock.yml'
        environment-name: test_env
        init-shell: powershell
        cache-downloads: true
        post-cleanup: none
