name: Setup poetry env
description: Setup poetry environment for Python
inputs:
  python_ver:
    description: 'Python version to use'
    required: true
    type: string
  shell_type:
    description: 'Shell type to use'
    required: false
    type: string
    default: 'bash'
  cache_number:
    description: 'Cache number to reset cache if poetry.lock has not changed'
    required: true
    type: number
  runner_os:
    description: 'Runner OS'
    required: true
    type: string

runs:
  using: "composite"
  defaults:
      run:
        shell: bash
  env:
    POETRY_VIRTUALENVS_CREATE: true
    POETRY_VIRTUALENVS_IN_PROJECT: true
  steps:
    - name: Get full Python version
      id: full-python-version
      run: echo "version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")" >> $GITHUB_OUTPUT
      # shell: ${{ inputs.shell_type }}
    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | POETRY_HOME=$HOME/.poetry python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      # shell: ${{ inputs.shell_type }}
    - name: Set up cache
      uses: actions/cache@v4
      id: cache
      env:
        CACHE_NUMBER: ${{ inputs.cache_number }}
      with:
        path: .venv
        key: venv-${{ inputs.runner_os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}-{{ inputs.CACHE_NUMBER }}
    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      run: timeout 10s poetry run pip --version || rm -rf .venv
      # shell: ${{ inputs.shell_type }}
    - name: Install dependencies
      run: poetry install -vvv
      # shell: ${{ inputs.shell_type }}