name: Setup poetry env
description: Setup poetry environment for Python
inputs:
  cache-number:
    description: 'Cache number to reset cache if poetry.lock has not changed'
    required: true
    type: number
  runner-os:
    description: 'Runner OS'
    required: true
    type: string
  virtual-repo-names:
    description: 'Matrix of virtual repository names to resolve (eg. ["public-dev-pypi"])'
    required: false
    type: string
  JFROG_ARTIFACTORY_TOKEN:
    description: 'JFrog Artifactory Token'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Get full Python version
      id: full-python-version
      run: echo "version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")" >> $GITHUB_OUTPUT
      shell: bash
    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | POETRY_HOME=$HOME/.poetry python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      shell: bash
    - name: Config poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true

        repository_list=$(echo '${{ inputs.virtual-repo-names }}' | jq -r '.[]')
        for repo_name in ${repository_list}; do
          first_part=$(echo "$repo_name" | cut -d'-' -f1 | tr '[:upper:]' '[:lower:]')
          echo "Adding repository $repo_name under $first_part"
          poetry config -- http-basic.${first_part} github ${{ inputs.JFROG_ARTIFACTORY_TOKEN }}
        done
      shell: bash
    - name: Set up cache
      uses: actions/cache@v4
      id: cache
      env:
        cache-number: ${{ inputs.cache-number }}
      with:
        path: .venv
        key: venv-${{ inputs.runner-os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}-{{ inputs.cache-number }}
    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      run: timeout 10s poetry run pip --version || rm -rf .venv
      shell: bash
    - name: Install dependencies
      run: poetry install -vvv
      shell: bash