name: Build conda package
description: Build a conda package with a meta.yaml file

inputs:
    python-version:
        description: 'Python version to use (eg: 3.10)'
        required: true
        type: string
outputs:
    dir-path:
        description: 'Path to the directory containing the built package'
        value: ${{ steps.build_package.outputs.dir-path }}

runs:
    using: "composite"
    steps:
        -   name: Set up Python version
            uses: actions/setup-python@v5
            with:
                python-version: ${{ inputs.python-version }}
        -   name: Check if there is a conda recipe
            run: |
                if [ -f meta.yaml ]; then
                    echo "Conda recipe found"
                else
                    echo "Conda recipe not found"
                    exit 1
                fi
            shell: bash
        -   name: Setup conda env
            uses: mamba-org/setup-micromamba@v1
            with:
                micromamba-version: 1.5.8-0
                environment-name: test_env
                init-shell: bash
                cache-downloads: true
            env:
                PYTHONUTF8: 1
                CONDA_CHANNEL_PRIORITY: strict
                PIP_NO_DEPS: 1 # all dependencies are installed from conda
        -   name: Install conda build
            run: conda install -y conda-build conda-verify
            shell: bash
        -   name: Build package
            id: build_package
            run: |
                    conda build . --output-folder dist
                    build_path=$(conda build --output . --output-folder dist)
                    dir_path=$(dirname "${build_path}")
                    echo "BUILD_PATH=${build_path}" >> $GITHUB_ENV
                    echo "dir-path=${dir_path}" >> $GITHUB_OUTPUT
            shell: bash
        -   name: Archive build artifact
            uses: actions/upload-artifact@v4
            with:
                name: package-build-conda
                path: ${{ env.BUILD_PATH }}
                retention-days: 7
