name: Build conda package
description: Build a conda package with a meta.yaml file

inputs:
    python-version:
        description: 'Python version to use (eg: 3.10)'
        required: true
        type: string
outputs:
    dir-path:
        description: 'Path to the directory containing the built package'
        value: ${{ steps.build-package.outputs.dir-path }}

runs:
    using: "composite"
    steps:
        -   name: Set up Python version
            uses: actions/setup-python@v5
            with:
                python-version: ${{ inputs.python-version }}
        -   name: Check if there is a conda recipe
            shell: bash
            run: |
                if [ -f meta.yaml ]; then
                    echo "Conda recipe found"
                else
                    echo "Conda recipe not found"
                    exit 1
                fi
        -   name: Setup conda env
            uses: mamba-org/setup-micromamba@v1
            with:
                micromamba-version: 1.5.8-0
                environment-name: test_env
                init-shell: bash
                cache-downloads: true
            env:
                PYTHONUTF8: 1
                CONDA_CHANNEL_PRIORITY: strict
        -   name: Install conda build
            run: conda install -y conda-build conda-verify
            shell: bash
        -   name: Build package
            id: build-package
            shell: bash
            run: |
                    conda build . --output-folder dist
                    BUILD_PATH=$(conda build --output . --output-folder dist)
                    DIR_PATH=$(dirname "${BUILD_PATH}")
                    echo "build-path=${BUILD_PATH}" >> $GITHUB_OUTPUT
                    echo "dir-path=$( echo $DIR_PATH)" >> $GITHUB_OUTPUT
        -   name: Archive build artifact
            uses: actions/upload-artifact@v4
            with:
                name: package-build-conda
                path: ${{ steps.build-package.outputs.build-path }}
                retention-days: 7
