name: Setup hatch env
description: Setup hatch environment for Python
inputs:
  cache_number:
    description: 'Cache number to reset cache if pyproject.toml has not changed'
    required: true
    type: number
  runner_os:
    description: 'Runner OS'
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Get full Python version
      id: full-python-version
      run: echo "version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")" >> $GITHUB_OUTPUT
      shell: bash
    - name: Set up cache
      uses: actions/cache@v4
      id: cache
      with:
        path: ~/.cache/pip
        key: venv-${{ inputs.runner_os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('piproject.toml') }}-${{ inputs.cache_number }}
    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      run: timeout 10s poetry run pip --version || rm -rf .venv
      shell: bash
    - name: Install hatch
      run: pip install hatch
      shell: bash
