name: Setup hatch env
description: Setup hatch environment for Python
inputs:
  cache-number:
    description: Cache number to reset cache if pyproject.toml has not changed
    required: true
    type: number
  runner-os:
    description: Runner OS
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Get full Python version
      id: full-python-version
      shell: bash
      run: echo "version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")" >> $GITHUB_OUTPUT
    - name: Set up cache
      uses: actions/cache@v4
      id: cache
      with:
        path: ~/.cache/pip
        key: venv-${{ inputs.runner-os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('piproject.toml') }}-${{ inputs.cache-number }}
    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: timeout 10s poetry run pip --version || rm -rf .venv
    - name: Install hatch
      shell: bash
      run: pip install hatch
