name: Get or Draft Release
description: Find or create a new draft release for the current tag
outputs:
  release-name:
    description: "The release name: newly created or existing one at the current tag"
    value: ${{ steps.get-or-draft-release.outputs.release-name}}
  version-tag:
    description: "The name of the current version tag"
    value: ${{ steps.get-or-draft-release.outputs.version-tag}}

runs:
  using: "composite"
  steps:
    - name: Get or Draft Release
      id: get-or-draft-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: >
        [[ "$GITHUB_REF" != refs/tags/v* ]]
        && { echo "Error: workflow is not running on a version tag" >&2; exit 1; }

        tag_name=${GITHUB_REF#refs/tags/}

        gh release view $tag_name 2> /dev/null
        || new_release_url=$(gh release create --draft
        $( echo $tag_name | grep -i -q '^v[0-9]\+\(\.[0-9]\+\)\+-[a-z]' && echo --prerelease )
        -t $tag_name
        $tag_name)

        [[ $new_release_url ]] && (echo "release-name=${new_release_url##https*/}" >> $GITHUB_OUTPUT)
        || (echo "release-name=$tag_name" >> $GITHUB_OUTPUT)

        echo "version-tag=$tag_name" >> $GITHUB_OUTPUT)
      shell: bash
