name: Build poetry package
description: Build a poetry package with a meta.yaml file

inputs:
    python-version:
        description: 'Python version to use (eg: 3.10)'
        required: true
        type: string
    extra-repository:
        description: 'Boolean to indicate if extra repository is needed'
        required: false
        type: boolean
        default: false
    repo-user:
        description: 'Repository username'
        required: false
        type: string
    repo-token:
        description: 'Repository token'
        required: false
        type: string

runs:
    using: "composite"
    steps:
        -   name: Set up Python version
            uses: actions/setup-python@v5
            with:
                python-version: ${{ inputs.python-version }}
        -   name: Setup poetry env
            uses: MiraGeoscience/CI-tools/.github/actions/reusable-python-setup_poetry@main
            with:
                cache-number: 20
                runner-os: ubuntu-latest
                extra-repository: ${{ inputs.extra-repository }}
                repo-user: ${{ inputs.repo-user }}
                repo-token: ${{ inputs.repo-token }}

        -   name: Build package
            id: build_package
            run: |
                    poetry build
            shell: bash
        -   name: Archive production artifacts
            uses: actions/upload-artifact@v4
            with:
                name: package-build-poetry
                path: dist
                retention-days: 7
