# File: template-test-minimal-conda-env-install.yml
stages:
  - stage: TestInstallationOnMinimalCondaEnv
    displayName: Test installation on minimal conda environment
    jobs:
      - job: DiscoverFiles
        displayName: 'Discover environment files package'
        steps:
          - task: PowerShell@2
            name: DiscoverFiles
            inputs:
              targetType: 'inline'
              script: |
                ls . #TODO: Debug
                $envFolder = "environments"
                $artifactFolder = "artifact_envFiles"
                $files = Get-ChildItem -Path $envFolder -Filter *.yml -Recurse
                if ($files.Count -eq 0) {
                  Write-Error "No environment files found in $envFolder"
                }
                $matrix = @{}
                if (!(Test-Path -Path $artifactFolder)) {
                    New-Item -ItemType Directory -Path '$(Build.ArtifactStagingDirectory)/$artifactFolder' | Out-Null
                }
                foreach ($file in $files) {
                  $key = [IO.Path]::GetFileNameWithoutExtension($file.FullName)
                  $matrix[$key] = @{ envFile = $file.FullName }
                  Copy-Item -Path $file.FullName -Destination $artifactFolder -Force
                }
                echo "##vso[task.setvariable variable=matrix;]$matrix"
                echo "You can use $matrix"
                $matrix | ConvertTo-Json -Depth 2 | Write-Host
          - publish: '$(DiscoverFiles.ArtifactStagingDirectory)'
            artifact: envFiles
            displayName: 'Publish environment files'

      - job: TestInstallationOnMinimalCondaEnv
        container:
          image: mirageoscienceltd.jfrog.io/mira-docker-local/windows-servercore-ltsc2022-miniforge:latest
          endpoint: Docker-Artifactory
        dependsOn: DiscoverFiles
        steps:
          - checkout: none
          - download: current
            artifact: envFiles
          - script: |
              ls '$(Pipeline.Workspace)/envFiles'
              echo $(matrix)
              conda create -y --verify-artifacts -f $(envFile)


