# File: template-test-minimal-conda-env-install.yml

stages:
  - stage: TestInstallationOnMinimalCondaEnv
    displayName: Test installation on minimal conda environment
    jobs:
      - job: DiscoverFiles
        displayName: 'Discover environment files package'
        steps:
          - task: PowerShell@2
            name: DiscoverFiles
            inputs:
              targetType: 'inline'
              script: |
                ls . #TODO: Debug
                $envFolder = "geopy-distrib/environments"
                $files = Get-ChildItem -Path $envFolder -Filter *.yml -Recurse
                if ($files.Count -eq 0) {
                  Write-Error "No environment files found in $envFolder"
                }
                $matrix = @{}
                foreach ($file in $files) {
                  $key = [IO.Path]::GetFileNameWithoutExtension($file.FullName)
                  $matrix[$key] = @{ envFile = $file.FullName }
                }
                echo "##vso[task.setvariable variable=matrix;]$matrix"
                echo "You can use $matrix"
      - job: InstallPackageWithEnvFile
        variables:
          envFile: $[ dependencies.DiscoverFiles.outputs['DiscoverFiles.matrix'] ]
        displayName: 'Install packages with environment file'
        container:
          image: mirageoscienceltd.jfrog.io/mira-docker-local/windows-servercore-ltsc2022-miniforge:latest
          endpoint: Docker-Artifactory
        steps:
          - script: |
              echo $(matrix)
              conda create -y --verify-artifacts -f $(envFile)


