# File: template-test-minimal-conda-env-install.yml

stages:
  - stage: TestInstallationOnMinimalCondaEnv
    displayName: Test installation on minimal conda environment
    jobs:
      - job: InstallPythonEnv
        displayName: 'Install python and miniforge'
        pool: 
          vmImage: 'windows-2022'
        container: 'mcr.microsoft.com/windows/servercore:ltsc2022'
        steps:
          - task: PowerShell@2
            displayName: 'Install miniforge'
            inputs:
              targetType: 'inline'
              script: |
                Invoke-WebRequest -Uri https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe -Outfile miniforge-installer.exe; Start-Process miniforge-installer.exe -ArgumentList: 'start /wait "" Miniforge3-Windows-x86_64.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniforge3' -NoNeWindow -Wait; Remove-Item -Force miniforge-installer.exe -Wait; Remove-Item -Force miniforge-installer.exe
      - job: DiscoverFiles
        displayName: 'Discover environment files package'
        steps:
          - task: PowerShell@2
            name: DiscoverFiles
            inputs:
              targetType: 'inline'
              script: |
                $envFolder = environments
                $files = Get-ChildItem -Path $envFolder -Filter *.yml -Recurse
                if ($files.Count -eq 0) {
                  Write-Error "No environment files found in $envFolder"
                }
                $matrix = @{}
                foreach ($file in $files) {
                  $key = [IO.Path]::GetFileNameWithoutExtension($file.FullName)
                  $matrix[$key] = @{ envFile = $file.FullName }
                }
                echo "##vso[task.setvariable variable=matrix;]$matrix"
                echo "You can use $(matrix)"
      - job: InstallPackageWithEnvFile
        variables:
          envFile: $[ dependencies.DiscoverFiles.outputs['DiscoverFiles.matrix'] ]
        strategy:
          matrix:
            envFile: $(matrix)
        displayName: 'Install packages with environment file'
        steps:
          - script: |
              micromamba.exe create -y --verify-artifacts -f $(envFile)


