name: Dependabot auto-merge

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers] no checkout, no execution of PR-authored code; only trusted event context is read
    types: [opened, synchronize, reopened]

jobs:
  call-workflow-dependabot-auto-merge:
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-dependabot-auto-merge.yml@DEVOPS-1061
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    with:
      dependabot-group: mirageo-ci-tools
      checks-to-skip: ''
