name: Add JIRA issue summary

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened]

jobs:
  call-workflow-add-jira-issue-summary:
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-jira-pr_add_jira_summary.yml@main
    secrets: inherit
