name: Add JIRA issue summary

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened]

jobs:
  call-workflow-add-jira-issue-summary:
    uses: ./.github/workflows/reusable-jira-pr_add_jira_summary.yml
    secrets: inherit
