name: Add JIRA issue summary

on:
  pull_request_target:
    types: [opened]

jobs:
  call-workflow-add-jira-issue-summary:
    uses: MiraGeoscience/CI-tools/github-workflows/jira/pr_add_jira_summary.yml
    secrets: inherit
