name: pre-commit

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**
  push:
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  call-workflow-pre-commmit:
    name: Pre-Commit
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-pre_commit.yml@DEVOPS-565-fixup2
  git-remotes:
    name: List git remotes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git remote -v
