name: Pytest on Windows

on:
  workflow_call:
    inputs:
      package-manager:
        description: 'Package manager to use (eg. "conda", "poetry")'
        required: true
        type: string
        default: 'poetry'
      python-versions:
        description: 'Matrix of Python versions to test against (eg. ["3.10", "3.11", "3.12"])'	
        required: false
        type: string
        default: "['3.10']"
      cache-number:
        description: 'Cache number to reset cache if poetry.lock has not changed'
        required: false
        type: number
        default: 1
      codecov-reference-python-version:
        description: 'Python version to use as reference for Codecov'
        required: false
        type: string
      extra-repository:
        description: 'Boolean to indicate if extra repository is needed'
        required: false
        type: boolean
        default: false
      lfs:
        description: 'Boolean to indicate if Github LFS is needed'
        required: false
        type: boolean
        default: false
      timeout-minutes:
        description: 'Timeout in minutes for the job'
        required: false
        type: number
        default: 20

    secrets:
      CODECOV_TOKEN:
        description: 'Codecov token'
        required: false
      EXTRA_PYPI_REPO_USER:
        description: 'Extra PyPI repository username. Only used if `extra-repository` is True.'
        required: false
      EXTRA_PYPI_REPO_TOKEN:
        description: 'Extra PyPI repository token. Only used if `extra-repository` is True.'
        required: false

jobs:
  pytest:
    name: Pytest (Windows)
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-pytest.yml@DEVOPS-471
    with:
      package-manager: ${{ inputs.package-manager }}
      python-versions: ${{ inputs.python-versions }}
      os: '["windows-latest"]'
      cache-number: ${{ inputs.cache-number }}
      codecov-reference-python-version: ${{ inputs.codecov-reference-python-version }}
      extra-repository: ${{ inputs.extra-repository }}
      lfs: ${{ inputs.lfs }}
      timeout-minutes: ${{ inputs.timeout-minutes }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      EXTRA_PYPI_REPO_USER: ${{ secrets.EXTRA_PYPI_REPO_USER }}
      EXTRA_PYPI_REPO_TOKEN: ${{ secrets.EXTRA_PYPI_REPO_TOKEN }}
