name: Publish condan package to Artifactory 

on:
  workflow_call:
    inputs:
        package_name:
            description: 'Name of the package to build'
            required: true
            type: string
        version_tag:
            description: 'Version tag of the package to build'
            required: true
            type: string
    secrets:
        EXTRA_REPO_TOKEN:
            description: 'Bearer token for the extra repository on JFrog Artifactory'
            required: true

defaults:
    run:
        shell: 'bash -l {0}'

jobs:
    build_package:
        name: build package
        runs-on: ubuntu-latest
        env:
            PYTHONUTF8: 1
            CONDA_CHANNEL_PRIORITY: strict
            PIP_NO_DEPS: 1 # all dependencies are installed from conda
            CONDA_LOCK_ENV_FILE: environments/py-3.10-linux-64-dev.conda.lock.yml
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   uses: MiraGeoscience/CI-tools/.github/actions/reusable-python-setup_conda@main
                name: Setup conda env
                with:
                  python_ver: '3.10'
            -   name: Install dependencies
                run: |
                    conda install -y grayskull
                    conda install -y conda-build
            -   name: Generate conda recipe
                run: |
                    tar czf ../${{inputs.package_name}}-${{inputs.version_tag}}.tar.gz .
                    grayskull pypi --tag ${{ inputs.version_tag }} ../${{ inputs.package_name }}-${{ inputs.version_tag }}.tar.gz
            -   name: Build package
                id: build_package
                run: |
                    conda build ${{ inputs.package_name }}
                    build_path=$(conda build --output ${{ inputs.package_name }})
                    build_name=$(basename ${build_path})
                    echo "BUILD_PATH=${build_path}" >> $GITHUB_OUTPUT
                    echo "BUILD_NAME=${build_name}" >> $GITHUB_OUTPUT
                    echo "BUILD_PATH=${build_path}" >> $GITHUB_ENV
                    echo "BUILD_NAME=${build_name}" >> $GITHUB_ENV	
            -   name: Test output
                run: | 
                    echo ${{ env.BUILD_PATH }}
                    echo ${{ env.BUILD_NAME }}
                    if test -f ${{ env.BUILD_PATH }}; then
                        echo "File exists"
                    else
                        echo "File does not exist"
                    fi
            -   name: Upload build package
                uses: actions/upload-artifact@v4
                with:
                    name: ${{ env.BUILD_NAME }}
                    path: ${{ env.BUILD_PATH }}
                    retention-days: 7
            # -   name: Check package
            #     run: |
            #         conda install $BUILD_PATH
        outputs:
            BUILD_PATH: ${{ steps.build_package.outputs.BUILD_PATH }}
    publish_package:
        name: publish package on artifactory
        needs: build_package
        runs-on: ubuntu-latest
        steps:
            -   name: Download build package
                uses: actions/download-artifact@v4
                with:
                    name: ${{ needs.build_package.outputs.BUILD_NAME }}
            -   name: Publish
                run: |
                    curl -T ${{ needs.build_package.outputs.BUILD_NAME }} -H "Authorization: Bearer ${{ secrets.EXTRA_REPO_TOKEN }}" "https://mirageoscienceltd.jfrog.io/artifactory/analyst-dev-conda-local/${{ inputs.package_name }}/${{ inputs.version_tag }}/${{ needs.build_package.outputs.BUILD_NAME }}"

            
            