name: Publish condan package to Artifactory 

on:
  workflow_call:
    inputs:
        package_name:
            description: 'Name of the package to build'
            required: true
            type: string
        version_tag:
            description: 'Version tag of the package to build'
            required: true
            type: string
    secrets:
        EXTRA_REPO_TOKEN:
            description: 'Bearer token for the extra repository on JFrog Artifactory'
            required: true

defaults:
    run:
        shell: 'bash -l {0}'

jobs:
    build-package:
        name: build package
        runs-on: ubuntu-latest
        env:
            PYTHONUTF8: 1
            CONDA_CHANNEL_PRIORITY: strict
            PIP_NO_DEPS: 1 # all dependencies are installed from conda
            CONDA_LOCK_ENV_FILE: environments/py-3.10-linux-64-dev.conda.lock.yml
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   uses: MiraGeoscience/CI-tools/.github/actions/reusable-python-setup_conda@main
                name: Setup conda env
                with:
                  python_ver: '3.10'
            -   name: Install dependencies
                run: |
                    conda intall -y grayskull
                    conda install -y conda-build
            -   name: Generate conda recipe
                run: |
                    grayskull pypi --tag ${{ inputs.version_tag }} ${{ inputs.package_name }}
                    conda-build check ${{ inputs.package_name }}
            -   name: Build package
                run: |
                    build_path=$(conda build --output ${{ inputs.package_name }})
                    echo "BUILD_PATH=${build_path}" >> $GITHUB_ENV
            -   name: Check package
                run: |
                    conda install $BUILD_PATH
    publish_package:
        name: publish package on artifactory
        runs-on: ubuntu-latest
        steps:
            -   name: Publish
                run: |
                    build_name=$(basename ${{ env.BUILD_PATH }})
                    curl -T ${{ env.BUILD_PATH }} -H "Authorization: Bearer ${{ secrets.EXTRA_REPO_TOKEN }}" "https://mirageoscienceltd.jfrog.io/artifactory/analyst-dev-conda-local/${{ inputs.package_name }}/${{ inputs.version_tag }}/${build_name}"

            
            