name: Pre-commit

on:
  workflow_call:
    inputs:
      app-name:
        description: 'Name of the app to run pre-commit on'
        required: false
        type: string
      os:
        description: 'Matrix of OS to run against (eg. ["ubuntu-latest", "macos-latest"])'
        required: false
        type: string
        default: "['ubuntu-latest']"
      python-version:
        description: 'Python version used with pre-commit'
        required: false
        type: string
        default: "3.10"
      timeout-minutes:
        description: 'Timeout in minutes for the job'
        required: false
        type: number
        default: 20

jobs:
  pre-commit:
    name: pre-commit
    if: ${{ (github.event_name != 'pull_request') || (github.event.pull_request.draft == false) }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}
    runs-on: ${{ matrix.os }}
    env:
      SKIP: pylint
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: capture modified files
        if: ${{ github.event_name == 'pull_request' }}
        run: >-
          git fetch --deepen=500 origin ${{github.base_ref}} && 
          if [ -n "${{ inputs.app-name}}"]; then
            echo "FILES_PARAM=$(
              git diff --diff-filter=AM --name-only refs/remotes/origin/${{github.base_ref}}... -- | grep -E "^(${{ inputs.app-name }}|tests)/.*\.py$" | xargs
            )" >> $GITHUB_ENV
          else
            echo "FILES_PARAM=$(
              git diff --diff-filter=AM --name-only refs/remotes/origin/${{github.base_ref}}... -- | xargs
            )" >> $GITHUB_ENV
          fi
          
      - name: Run pre-commit on modified files
        if: ${{ (github.event_name == 'pull_request') && (env.FILES_PARAM) }}
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --hook-stage pre-push --files ${{ env.FILES_PARAM }}
      - name: Run pre-commit on all files
        if: ${{ github.event_name == 'push' }}
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --hook-stage pre-push --all-files
