name: Pre-commit

on:
  workflow_call:
    inputs:
      app_name:
        description: 'Name of the app to run pre-commit on'
        required: false
        type: string

jobs:
  pre-commit:
    name: pre-commit
    if: ${{ (github.event_name != 'pull_request') || (github.event.pull_request.draft == false) }}
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      SKIP: pylint
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: capture modified files
        if: ${{ github.event_name == 'pull_request' }}
        run: >-
          git fetch --deepen=500 origin ${{github.base_ref}} && 
          if [ -n "${{ inputs.app_name}}"]; then
            echo "FILES_PARAM=$(
              git diff --diff-filter=AM --name-only refs/remotes/origin/${{github.base_ref}}... -- | grep -E "^(${{ inputs.app_name }}|tests)/.*\.py$" | xargs
            )" >> $GITHUB_ENV
          else
            echo "FILES_PARAM=$(
              git diff --diff-filter=AM --name-only refs/remotes/origin/${{github.base_ref}}... -- | xargs
            )" >> $GITHUB_ENV
          fi
          
      - name: Run pre-commit on modified files
        if: ${{ (github.event_name == 'pull_request') && (env.FILES_PARAM) }}
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --hook-stage push --files ${{ env.FILES_PARAM }}
      - name: Run pre-commit on all files
        if: ${{ github.event_name == 'push' }}
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --hook-stage push --all-files
      - uses: pre-commit-ci/lite-action@v1.0.2
        if: always()
