name: MSDO analysis

on:
  workflow_call:

jobs:
  msdo:
    name: Security Scan
    if: ${{ (github.event_name != 'pull_request') || (github.event.pull_request.draft == false) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Run Microsoft Security DevOps Analysis
        id: msdo
        continue-on-error: true
        uses: microsoft/security-devops-action@v1

      - name: Upload SARIF to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

