name: Publish condan package to Artifactory 

on:
  workflow_call:
    inputs:
        package_name:
            description: 'Name of the package to build'
            required: true
            type: string
        python_ver:
            description: 'Python version to use (eg: 3.10)'
            required: true
            type: string
        version_tag:
            description: 'Version tag of the package to build'
            required: true
            type: string
    secrets:
        EXTRA_REPO_TOKEN:
            description: 'Bearer token for the extra repository on JFrog Artifactory'
            required: true

defaults:
    run:
        shell: 'bash -l {0}'

jobs:
    build_package:
        name: build package
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-lastest, windows-latest]
        runs-on: ${{ matrix.os }}
        env:
            PYTHONUTF8: 1
            CONDA_CHANNEL_PRIORITY: strict
            PIP_NO_DEPS: 1 # all dependencies are installed from conda
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup CONDA_LOCK_ENV_FILE
                run: |
                    os_conda=$( [[ $RUNNER_OS == "Linux" ]] && echo "linux" || ([[ $RUNNER_OS == "Windows" ]] && echo "win" || echo "osx"))
                    echo "CONDA_LOCK_ENV_FILE=environments/py-${{ inputs.python_ver }}-${os_conda}-64-dev.conda.lock.yml" >> $GITHUB_ENV
            -   uses: MiraGeoscience/CI-tools/.github/actions/reusable-python-setup_conda@main
                name: Setup conda env
                with:
                  python_ver: ${{ inputs.python_ver }}
            -   name: Install dependencies
                run: |
                    conda install -y grayskull
                    conda install -y conda-build
                    conda install -y conda-verify
            -   name: Generate conda recipe
                run: |
                    tar czf ../${{inputs.package_name}}-${{inputs.version_tag}}.tar.gz .
                    grayskull pypi ../${{ inputs.package_name }}-${{ inputs.version_tag }}.tar.gz
            -   name: Build package
                id: build_package
                run: |
                    conda build ${{ inputs.package_name }}
                    build_path=$(conda build --output ${{ inputs.package_name }})
                    build_name=$(basename ${build_path})
                    echo "BUILD_PATH=${build_path}" >> $GITHUB_OUTPUT
                    echo "BUILD_NAME=${build_name}" >> $GITHUB_OUTPUT
                    echo "BUILD_PATH=${build_path}" >> $GITHUB_ENV
                    echo "BUILD_NAME=${build_name}" >> $GITHUB_ENV	
            -   name: Upload build package
                uses: actions/upload-artifact@v4
                with:
                    name: ${{ env.BUILD_NAME }}
                    path: ${{ env.BUILD_PATH }}
                    retention-days: 7
        outputs:
            BUILD_PATH: ${{ steps.build_package.outputs.BUILD_PATH }}
            BUILD_NAME: ${{ steps.build_package.outputs.BUILD_NAME }}
    publish_package:
        name: publish package on artifactory
        needs: build_package
        runs-on: ubuntu-latest
        steps:
            -   name: Download build package
                uses: actions/download-artifact@v4
                with:
                    name: ${{ needs.build_package.outputs.BUILD_NAME }}
            -   name: Publish
                run: |
                    curl -T ${{ needs.build_package.outputs.BUILD_NAME }} -H "Authorization: Bearer ${{ secrets.EXTRA_REPO_TOKEN }}" "https://mirageoscienceltd.jfrog.io/artifactory/analyst-dev-conda-local/${{ inputs.package_name }}/${{ inputs.version_tag }}/${{ needs.build_package.outputs.BUILD_NAME }}"

            
            