name: Publish conda package to Artifactory 

on:
  workflow_call:
    inputs:
        package-name:
            description: 'Name of the package to build'
            required: true
            type: string
        python-version:
            description: 'Python version to use (eg: 3.10)'
            required: true
            type: string
        lfs:
            description: 'Boolean to indicate if Github LFS is needed'
            required: false
            type: boolean
            default: false
        virtual-repo-name:
            description: 'Name of the virtual repository to publish on (eg. "public-dev-conda")'
            required: true
            type: string
        os:
            description: 'OS to build against (eg. "ubuntu-latest")'
            required: false
            type: string
            default: 'ubuntu-latest'
        timeout-minutes:
            description: 'Timeout in minutes for the job'
            required: false
            type: number
            default: 20

    secrets:
        JFROG_ARTIFACTORY_URL:
            description: 'JFrog Artifactory URL'
            required: true
        JFROG_ARTIFACTORY_TOKEN:
            description: 'JFrog Artifactory Token'
            required: true

defaults:
    run:
        shell: 'bash -l {0}'

jobs:
    build_package:
        name: Build package
        runs-on: ${{ inputs.os }}
        timeout-minutes: ${{ inputs.timeout-minutes }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    lfs: ${{ inputs.lfs }}
                    fetch-depth: 0
            -   name: Check if there is a conda recipe
                run: |
                    if [ -f meta.yaml ]; then
                        echo "Conda recipe found"
                    else
                        echo "Conda recipe not found"
                        exit 1
                    fi
            -   name: Set up Python version
                uses: actions/setup-python@v5
                with:
                    python-version: ${{ inputs.python-version }}
            -   uses: jfrog/setup-jfrog-cli@v4.4.1
                name: Setup JFrog CLI
                env:
                    JF_URL: https://${{ secrets.JFROG_ARTIFACTORY_URL }}
                    JF_ACCESS_TOKEN: ${{ secrets.JFROG_ARTIFACTORY_TOKEN }}
            
            -   name: Setup conda env
                uses: mamba-org/setup-micromamba@v1
                with:
                    micromamba-version: 1.5.8-0
                    environment-name: test_env
                    init-shell: bash
                    cache-downloads: true
                env:
                    PYTHONUTF8: 1
                    CONDA_CHANNEL_PRIORITY: strict
            -   name: Add conda channel
                run: conda config --add channels https://github:${{ secrets.JFROG_ARTIFACTORY_TOKEN }}@${{ secrets.JFROG_ARTIFACTORY_URL }}/artifactory/api/conda/${{ inputs.virtual-repo-name}}
            -   name: Install conda build
                run: conda install -y conda-build conda-verify
            -   name: Build package
                id: build-package
                run: |
                    conda build .
                    BUILD_PATH=$(conda build --output .)
                    if [[ -z ${BUILD_PATH} ]]; then
                        echo "No build path found"
                        exit 1
                    fi
                    echo "build-path=${BUILD_PATH}" >> $GITHUB_OUTPUT
            
            -   name: Archive build artifact
                uses: actions/upload-artifact@v4
                with:
                    name: package-build-conda
                    path: ${{ steps.build-package.outputs.build-path }}
                    retention-days: 7
            -   name: Publish package to Artifactory
                run: |
                    file="${{ steps.build-package.outputs.build-path }}"
                    filename=$(basename "${file}") 
                    echo "Uploading in ${{ inputs.virtual-repo-name }}/noarch: $filename"
                    jf rt u ${file} ${{ inputs.virtual-repo-name }}/noarch/${filename}
