name: Pytest on Unix OS

on:
  workflow_call:
    inputs:
      package_manager:
        description: 'Package manager to use (eg. "conda", "poetry")'
        required: true
        type: string
        default: 'poetry'
      python_ver:
        description: 'Matrix of Python versions to test against (eg. ["3.10", "3.11", "3.12"])'	
        required: false
        type: string
        default: "['3.10']"
      os:
        description: 'Matrix of OS to test against (eg. ["ubuntu-latest", "macos-latest"])'
        required: false
        type: string
        default: "['ubuntu-latest']"
      cache_number:
        description: 'Cache number to reset cache if poetry.lock has not changed'
        required: false
        type: number
        default: 1

jobs:
  pytest:
    name: pytest
    if: ${{ (github.event_name != 'pull_request') || (github.event.pull_request.draft == false) }}
    strategy:
      fail-fast: false
      matrix:
        python_ver: ${{ fromJSON(inputs.python_ver) }}
        os: ${{ fromJSON(inputs.os) }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_ver }}
      
      - uses: MiraGeoscience/CI-tools/.github/actions/reusable-python-setup_conda@DEVOPS-459
        name: Setup conda env
        if: ${{ inputs.package_manager == 'conda' }}
        with:
          python_ver: ${{ matrix.python_ver }}
          shell_type: 'bash'
      - uses: MiraGeoscience/CI-tools/.github/actions/reusable-python-setup_poetry@DEVOPS-459
        name: Setup poetry env
        if: ${{ inputs.package_manager == 'poetry' }}
        with:
          python_ver: ${{ matrix.python_ver }}
          cache_number: ${{ inputs.cache_number }}
          runner_os: ${{ runner.os }}
        
      - name: Run Pytest (with poetry)
        if : ${{ inputs.package_manager == 'poetry' }}
        run: |
          RUNNER=$( ${{ inputs.package_manager == 'conda' }} ? '' : 'poetry run' })
          $(${RUNNER} pytest --cov --cov-report=xml)
      - name: Run Pytest (with conda)
        if : ${{ inputs.package_manager == 'conda' }}
        run: |
          RUNNER=$( ${{ inputs.package_manager == 'conda' }} ? '' : 'poetry run' })
          $(${RUNNER} pytest --cov --cov-report=xml)
        