name: Zizmor Security Scan
on:
 pull_request:
   types: [opened, synchronize, reopened, ready_for_review]
   branches:
     - development
     - main
     - release/**
     - feature/**
     - hotfix/**
 push:
   branches:
     - development
     - main
     - release/**
     - feature/**
     - hotfix/**
jobs:
 security_scan:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     actions: read
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
       with:
         persist-credentials: false
     - name: Run Zizmor Security Scan
       uses: zizmorcore/zizmor-action@f52a838cfabf134edcbaa7c8b3677dde20045018
       with:
         advanced-security: false
