name: Setup Zizmor Config
description: Creates a default zizmor.yml if one does not exist
runs:
  using: composite
  steps:
    - name: Ensure default zizmor.yml
      shell: bash
      run: |
        # Create zizmor config if missing
        if [[ ! -f zizmor.yml ]]; then
          echo "Creating a custom zizmor.yml configuration file for CI..."
          echo $'rules:\n' > zizmor.yml
        fi

        # Patch (merge) with extra config
        echo "Patching zizmor.yml configuration file for CI..."
        yq -i '
          .rules |= (. // {}) |
          .rules."dependabot-cooldown" |= (. // {}) |
          .rules."dependabot-cooldown".disable |= true |
          .rules."unpinned-uses" |= (. // {}) |
          .rules."unpinned-uses".config |= (. // {}) |
          .rules."unpinned-uses".config.policies |= (. // {}) |
          .rules."unpinned-uses".config.policies."MiraGeoscience/*" |= "ref-pin"
        ' zizmor.yml
