name: Setup Zizmor Config
description: Creates a default zizmor.yml if one does not exist
runs:
  using: composite
  steps:
    - name: Ensure default zizmor.yml
      shell: bash
      run: |
        if [[ ! -f zizmor.yml || $(wc -l < zizmor.yml) -eq 1 ]]; then
          echo "Creating a custom zizmor.yml configuration file for CI..."
          cat > zizmor.yml << 'EOF'
        rules:
          dependabot-cooldown:
            disable: true
          unpinned-uses:
            config:
              policies:
                MiraGeoscience/*: any
        EOF
        else
          echo "⊘ Found existing zizmor.yml configuration file"
        fi
